Hai 182 validointi
City-of-Helsinki/haitaton-backend pull request #43
Opened 2020-11-17 11:08 UTC by tintotti

Added validation mechanism for HankeController and tests for it. Rules are yet to be defined for the validation of each field.
Some changes to how HankeControllerTest is set up because we want to use the validation also in the unit level tests.

2020-11-17 11:34 UTC, umeetiusbaar requested changes

2020-11-17 11:34 UTC, umeetiusbaar commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
> +            HankeError.HAI1011
HAI1011 on Hankkeen geometrian tallennukseen liittyvä virhe (ks. https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/1006469173/Virheiden+hallinta - ja päivitä myös tuo sivu samoin kuin https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/981696609/Hanke+API+UI+lle).

2020-11-17 11:34 UTC, umeetiusbaar commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +        return input == null || input.trim { it <= ' ' }.length == 0
Sopisiko tähän kotlinin oma String?.isNullOrBlank-funktio? https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-null-or-blank.html
Muutenkin voisi olla luettavampaa tehdä extension-funktio, jos tarvitsee tällaisia omia funktioita tehdä.

2020-11-17 11:34 UTC, umeetiusbaar commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +        if (input == null) return false
Funktion nimessä on AllowNull, mutta jos on null, niin palauttaa false? Eli mitä tämä funktio oikein tarkistaa?

2020-11-17 11:34 UTC, umeetiusbaar commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +            context.buildConstraintViolationWithTemplate(HankeError.HAI1017.name).addConstraintViolation()
Mä toivoisin, että Hanketta koskien virhekoodit olisivat 1001-1010 - ei niin iso ongelma, kunhan wiki-sivu on ajan tasalla: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/1006469173/Virheiden+hallinta

2020-11-17 12:09 UTC, tintotti commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
> +            HankeError.HAI1011
Näköjään jäänyt tuo kohta väärin copypastesta, vaikka muka katsoin, että geometriaratkaisu on käytettävissä sellaisenaan.

2020-11-17 12:18 UTC, tintotti commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +        if (input == null) return false
Nimeäminen näköjään molemmilla validointicheckeillä ihan hassusti.

2020-11-17 12:18 UTC, tintotti commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +            context.buildConstraintViolationWithTemplate(HankeError.HAI1017.name).addConstraintViolation()
Päivitin sivun ja muutin koodiarvot.

2020-11-18 06:24 UTC, tintotti commented on services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
> +        if (input == null) return false
Tämä helpottuikin, eikä metodeita tässä vaiheessa tarvitakaan.

2020-11-18 07:26 UTC, merged